[package]
name = "murk"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.11.2"
base64 = "0.22.1"
bech32 = "0.9"
bip39 = "2.2.2"
clap = { version = "4.5.60", features = ["derive", "env"] }
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
