[changelog]
header = """
# Changelog\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/iicky/murk
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% endfor %}
{% endfor %}\n
"""
footer = ""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^add", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^doc", group = "Documentation" },
  { message = "^refactor", group = "Changed" },
  { message = "^bump", group = "Changed" },
  { message = "^update", group = "Changed" },
  { message = "^use", group = "Changed" },
  { message = "^graceful", group = "Changed" },
  { message = "^extract", group = "Changed" },
  { message = "^Merge", skip = true },
  { message = "^Bump", skip = true },
  { message = "^cargo fmt", skip = true },
  { body = ".*", group = "Other" },
]
filter_commits = true
commit_preprocessors = [
  { pattern = "\\(#\\d+\\)", replace = "" },
]
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
